In [28]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv("../Dataset/ecommerce_sales_dataset.csv")

In [30]:
df.head()

,Order_ID,Order_Date,Year,Month,Quarter,Season,Customer_ID,Customer_Gender,Customer_Segment,Region,...,Discount,Revenue,Cost,Profit,Profit_Margin_%,Shipping_Cost,Shipping_Method,Shipping_Days,Payment_Method,Order_Status
0,ORD-000001,2023-01-18,2023,1,Q1,Winter,CUST-02791,Male,New,North America,...,0.00,3642.80,2444.11,1198.69,32.91,2.25,Economy,4,Google Pay,Delivered
1,ORD-000002,2023-11-13,2023,11,Q4,Fall,CUST-02763,Female,Regular,North America,...,0.25,33.88,28.32,5.56,16.41,4.72,Economy,5,Credit Card,Delivered
2,ORD-000003,2022-04-28,2022,4,Q2,Spring,CUST-05729,Male,Regular,North America,...,0.00,241.30,161.41,79.89,33.11,13.28,Standard,8,Credit Card,Processing
3,ORD-000004,2021-10-22,2021,10,Q4,Fall,CUST-06490,Female,Regular,Asia,...,0.00,654.50,369.16,285.34,43.60,31.11,Express,16,Google Pay,Processing
4,ORD-000005,2023-08-06,2023,8,Q3,Summer,CUST-07594,Female,Premium,Europe,...,0.20,178.82,118.69,60.13,33.63,8.44,Standard,5,Debit Card,Delivered

In [31]:
df.shape

(10000, 26)

In [32]:
df.columns

Index(['Order_ID', 'Order_Date', 'Year', 'Month', 'Quarter', 'Season',
       'Customer_ID', 'Customer_Gender', 'Customer_Segment', 'Region',
       'Country', 'Category', 'Sub_Category', 'Product_Name', 'Unit_Price',
       'Quantity', 'Discount', 'Revenue', 'Cost', 'Profit', 'Profit_Margin_%',
       'Shipping_Cost', 'Shipping_Method', 'Shipping_Days', 'Payment_Method',
       'Order_Status'],
      dtype='str')

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          10000 non-null  str
 1   Order_Date        10000 non-null  str
 2   Year              10000 non-null  int64
 3   Month             10000 non-null  int64
 4   Quarter           10000 non-null  str
 5   Season            10000 non-null  str
 6   Customer_ID       10000 non-null  str
 7   Customer_Gender   10000 non-null  str
 8   Customer_Segment  10000 non-null  str
 9   Region            10000 non-null  str
 10  Country           10000 non-null  str
 11  Category          10000 non-null  str
 12  Sub_Category      10000 non-null  str
 13  Product_Name      10000 non-null  str
 14  Unit_Price        10000 non-null  float64
 15  Quantity          10000 non-null  int64
 16  Discount          10000 non-null  float64
 17  Revenue           10000 non-null  float64
 18  Cost              10000 non-null  float64
 19  Profit            10000 non-null  float64
 20  Profit_Margin_%   10000 non-null  float64
 21  Shipping_Cost     10000 non-null  float64
 22  Shipping_Method   10000 non-null  str
 23  Shipping_Days     10000 non-null  int64
 24  Payment_Method    10000 non-null  str
 25  Order_Status      10000 non-null  str
dtypes: float64(7), int64(4), str(15)
memory usage: 2.0 MB

In [34]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Year                0
Month               0
Quarter             0
Season              0
Customer_ID         0
Customer_Gender     0
Customer_Segment    0
Region              0
Country             0
Category            0
Sub_Category        0
Product_Name        0
Unit_Price          0
Quantity            0
Discount            0
Revenue             0
Cost                0
Profit              0
Profit_Margin_%     0
Shipping_Cost       0
Shipping_Method     0
Shipping_Days       0
Payment_Method      0
Order_Status        0
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df.nunique().sort_values()

Customer_Gender         2
Year                    4
Quarter                 4
Season                  4
Region                  4
Customer_Segment        4
Order_Status            4
Shipping_Method         4
Category                5
Payment_Method          7
Discount                9
Quantity               10
Month                  12
Sub_Category           14
Country                18
Shipping_Days          23
Product_Name           70
Order_Date           1355
Profit_Margin_%      5263
Shipping_Cost        5276
Customer_ID          5348
Profit               7973
Unit_Price           8391
Cost                 8824
Revenue              9066
Order_ID            10000
dtype: int64

In [38]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [39]:
df["Order_Date"].dtype

dtype('<M8[us]')

In [42]:
print("Start Date:", df["Order_Date"].min())
print("End Date:", df["Order_Date"].max())

Start Date: 2021-01-05 00:00:00
End Date: 2024-12-24 00:00:00

In [44]:
df[[
    "Quantity",
    "Unit_Price",
    "Discount",
    "Revenue",
    "Cost",
    "Profit",
    "Profit_Margin_%",
    "Shipping_Cost"
]].describe()

,Quantity,Unit_Price,Discount,Revenue,Cost,Profit,Profit_Margin_%,Shipping_Cost
count,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2.731300,236.307452,0.17675,528.438770,384.674939,143.763831,23.648594,32.299889
std,2.038508,380.901351,0.16167,1154.811538,828.069100,420.487992,21.496639,28.424003
min,1.000000,10.010000,0.00000,5.330000,4.850000,-1572.900000,-50.000000,2.000000
25%,1.000000,42.767500,0.00000,67.227500,50.017500,9.007500,13.497500,8.260000
50%,2.000000,92.495000,0.15000,164.600000,121.395000,34.745000,28.330000,20.300000
75%,4.000000,221.822500,0.30000,469.952500,339.020000,118.475000,39.082500,50.362500
max,10.000000,2497.760000,0.50000,19966.500000,15729.670000,9144.150000,54.990000,99.990000

In [45]:
print("Negative/Zero Quantity:", (df["Quantity"] <= 0).sum())
print("Negative Unit Price:", (df["Unit_Price"] <= 0).sum())
print("Invalid Discount:", ((df["Discount"] < 0) | (df["Discount"] > 1)).sum())
print("Negative Revenue:", (df["Revenue"] < 0).sum())
print("Negative Cost:", (df["Cost"] < 0).sum())
print("Negative Profit:", (df["Profit"] < 0).sum())
print("Negative Shipping Cost:", (df["Shipping_Cost"] < 0).sum())

Negative/Zero Quantity: 0
Negative Unit Price: 0
Invalid Discount: 0
Negative Revenue: 0
Negative Cost: 0
Negative Profit: 1338
Negative Shipping Cost: 0

In [46]:
calculated_profit = df["Revenue"] - df["Cost"]

profit_difference = calculated_profit - df["Profit"]

print("Maximum difference:", profit_difference.abs().max())
print("Rows with difference > 0.01:", (profit_difference.abs() > 0.01).sum())

Maximum difference: 1.8189894035458565e-12
Rows with difference > 0.01: 0

In [47]:
print("Start Date:", df["Order_Date"].min())
print("End Date:", df["Order_Date"].max())
print("Number of Years:", df["Year"].nunique())
print("Years:", sorted(df["Year"].unique()))

Start Date: 2021-01-05 00:00:00
End Date: 2024-12-24 00:00:00
Number of Years: 4
Years: [np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]

In [48]:
date_check = pd.DataFrame({
    "Year_from_Date": df["Order_Date"].dt.year,
    "Year_Column": df["Year"],
    "Month_from_Date": df["Order_Date"].dt.month,
    "Month_Column": df["Month"]
})

print("Year mismatches:", 
      (date_check["Year_from_Date"] != date_check["Year_Column"]).sum())

print("Month mismatches:", 
      (date_check["Month_from_Date"] != date_check["Month_Column"]).sum())

Year mismatches: 0
Month mismatches: 0

In [49]:
categorical_cols = [
    "Customer_Gender",
    "Customer_Segment",
    "Region",
    "Country",
    "Category",
    "Sub_Category",
    "Shipping_Method",
    "Payment_Method",
    "Order_Status"
]

for col in categorical_cols:
    print(f"\n{col}:")
    print(df[col].value_counts())

Customer_Gender:
Customer_Gender
Female    5097
Male      4903
Name: count, dtype: int64

Customer_Segment:
Customer_Segment
Regular    5073
Premium    1961
New        1942
VIP        1024
Name: count, dtype: int64

Region:
Region
North America    2602
Asia             2494
Middle East      2458
Europe           2446
Name: count, dtype: int64

Country:
Country
Mexico          897
Canada          876
USA             829
India           523
China           516
UK              513
Italy           512
UAE             510
Jordan          509
Kuwait          502
Germany         491
South Korea     486
Singapore       485
Japan           484
Egypt           481
Spain           469
France          461
Saudi Arabia    456
Name: count, dtype: int64

Category:
Category
Books & Media      2043
Home & Kitchen     2008
Beauty & Health    1995
Electronics        1977
Clothing           1977
Name: count, dtype: int64

Sub_Category:
Sub_Category
Skincare         1044
Books            1022
Software         1021
Supplements       951
Women's Wear      688
Appliances        683
Kitchen Tools     671
Furniture         654
Men's Wear        647
Footwear          642
Smartphones       514
Tablets           498
Laptops           486
Headphones        479
Name: count, dtype: int64

Shipping_Method:
Shipping_Method
Overnight    2522
Economy      2516
Express      2504
Standard     2458
Name: count, dtype: int64

Payment_Method:
Payment_Method
Debit Card          1486
PayPal              1470
Credit Card         1430
Bank Transfer       1426
Google Pay          1422
Cash on Delivery    1414
Apple Pay           1352
Name: count, dtype: int64

Order_Status:
Order_Status
Delivered     6273
Returned      1857
Processing     962
Cancelled      908
Name: count, dtype: int64

In [50]:
for col in [
    "Country",
    "Category",
    "Sub_Category",
    "Shipping_Method",
    "Payment_Method",
    "Order_Status"
]:
    print(f"\n{'='*40}")
    print(col)
    print(df[col].value_counts())

========================================
Country
Country
Mexico          897
Canada          876
USA             829
India           523
China           516
UK              513
Italy           512
UAE             510
Jordan          509
Kuwait          502
Germany         491
South Korea     486
Singapore       485
Japan           484
Egypt           481
Spain           469
France          461
Saudi Arabia    456
Name: count, dtype: int64

========================================
Category
Category
Books & Media      2043
Home & Kitchen     2008
Beauty & Health    1995
Electronics        1977
Clothing           1977
Name: count, dtype: int64

========================================
Sub_Category
Sub_Category
Skincare         1044
Books            1022
Software         1021
Supplements       951
Women's Wear      688
Appliances        683
Kitchen Tools     671
Furniture         654
Men's Wear        647
Footwear          642
Smartphones       514
Tablets           498
Laptops           486
Headphones        479
Name: count, dtype: int64

========================================
Shipping_Method
Shipping_Method
Overnight    2522
Economy      2516
Express      2504
Standard     2458
Name: count, dtype: int64

========================================
Payment_Method
Payment_Method
Debit Card          1486
PayPal              1470
Credit Card         1430
Bank Transfer       1426
Google Pay          1422
Cash on Delivery    1414
Apple Pay           1352
Name: count, dtype: int64

========================================
Order_Status
Order_Status
Delivered     6273
Returned      1857
Processing     962
Cancelled      908
Name: count, dtype: int64

In [51]:
for col in [
    "Category",
    "Sub_Category",
    "Shipping_Method",
    "Payment_Method",
    "Order_Status"
]:
    print(f"\n{col} → {df[col].nunique()} unique values")
    print(df[col].unique())

Category → 5 unique values
<StringArray>
['Electronics', 'Books & Media', 'Clothing', 'Home & Kitchen',
 'Beauty & Health']
Length: 5, dtype: str

Sub_Category → 14 unique values
<StringArray>
[  'Smartphones',         'Books',    'Headphones',  'Women's Wear',
      'Footwear',    'Men's Wear',     'Furniture',      'Software',
       'Laptops',      'Skincare',    'Appliances',   'Supplements',
       'Tablets', 'Kitchen Tools']
Length: 14, dtype: str

Shipping_Method → 4 unique values
<StringArray>
['Economy', 'Standard', 'Express', 'Overnight']
Length: 4, dtype: str

Payment_Method → 7 unique values
<StringArray>
[      'Google Pay',      'Credit Card',       'Debit Card',
        'Apple Pay', 'Cash on Delivery',           'PayPal',
    'Bank Transfer']
Length: 7, dtype: str

Order_Status → 4 unique values
<StringArray>
['Delivered', 'Processing', 'Returned', 'Cancelled']
Length: 4, dtype: str

In [56]:
print("Order Status:")
print(df["Order_Status"].value_counts())

print("\nPayment Method:")
print(df["Payment_Method"].value_counts())

print("\nCategory:")
print(df["Category"].value_counts())

print("\nCountry:")
print(df["Country"].value_counts())

Order Status:
Order_Status
Delivered     6273
Returned      1857
Processing     962
Cancelled      908
Name: count, dtype: int64

Payment Method:
Payment_Method
Debit Card          1486
PayPal              1470
Credit Card         1430
Bank Transfer       1426
Google Pay          1422
Cash on Delivery    1414
Apple Pay           1352
Name: count, dtype: int64

Category:
Category
Books & Media      2043
Home & Kitchen     2008
Beauty & Health    1995
Electronics        1977
Clothing           1977
Name: count, dtype: int64

Country:
Country
Mexico          897
Canada          876
USA             829
India           523
China           516
UK              513
Italy           512
UAE             510
Jordan          509
Kuwait          502
Germany         491
South Korea     486
Singapore       485
Japan           484
Egypt           481
Spain           469
France          461
Saudi Arabia    456
Name: count, dtype: int64

In [55]:
print("Order Status:", df["Order_Status"].unique())
print("Payment Method:", df["Payment_Method"].unique())
print("Category:", df["Category"].unique())
print("Country:", df["Country"].unique())

Order Status: <StringArray>
['Delivered', 'Processing', 'Returned', 'Cancelled']
Length: 4, dtype: str
Payment Method: <StringArray>
[      'Google Pay',      'Credit Card',       'Debit Card',
        'Apple Pay', 'Cash on Delivery',           'PayPal',
    'Bank Transfer']
Length: 7, dtype: str
Category: <StringArray>
['Electronics', 'Books & Media', 'Clothing', 'Home & Kitchen',
 'Beauty & Health']
Length: 5, dtype: str
Country: <StringArray>
[      'Mexico',          'USA',       'Canada',        'Japan',
       'France',        'China',      'Germany',       'Jordan',
        'Italy',        'Egypt',       'Kuwait',    'Singapore',
          'UAE',  'South Korea', 'Saudi Arabia',           'UK',
        'Spain',        'India']
Length: 18, dtype: str

In [57]:
category_subcategory_check = (
    df.groupby("Category")["Sub_Category"]
      .nunique()
      .sort_values()
)

category_subcategory_check

Category
Beauty & Health    2
Books & Media      2
Clothing           3
Home & Kitchen     3
Electronics        4
Name: Sub_Category, dtype: int64

In [58]:
pd.crosstab(df["Category"], df["Sub_Category"])

Sub_Category,Appliances,Books,Footwear,Furniture,Headphones,Kitchen Tools,Laptops,Men's Wear,Skincare,Smartphones,Software,Supplements,Tablets,Women's Wear
Category,,,,,,,,,,,,,,
Beauty & Health,0,0,0,0,0,0,0,0,1044,0,0,951,0,0
Books & Media,0,1022,0,0,0,0,0,0,0,0,1021,0,0,0
Clothing,0,0,642,0,0,0,0,647,0,0,0,0,0,688
Electronics,0,0,0,0,479,0,486,0,0,514,0,0,498,0
Home & Kitchen,683,0,0,654,0,671,0,0,0,0,0,0,0,0

In [59]:
for category, subcats in df.groupby("Category")["Sub_Category"].unique().items():
    print(f"\n{category}:")
    print(sorted(subcats))

Beauty & Health:
['Skincare', 'Supplements']

Books & Media:
['Books', 'Software']

Clothing:
['Footwear', "Men's Wear", "Women's Wear"]

Electronics:
['Headphones', 'Laptops', 'Smartphones', 'Tablets']

Home & Kitchen:
['Appliances', 'Furniture', 'Kitchen Tools']

In [60]:
df[
    (df["Category"] == "Books & Media") &
    (df["Sub_Category"] == "Software")
].shape

(1021, 26)

In [61]:
df[
    (df["Category"] == "Books & Media") &
    (df["Sub_Category"] == "Software")
][[
    "Category",
    "Sub_Category",
    "Product_Name",
    "Revenue",
    "Profit"
]].head(20)

          Category Sub_Category          Product_Name  Revenue  Profit
10   Books & Media     Software  Microsoft Office 365   221.97   66.85
16   Books & Media     Software   Photo Editing Suite  1134.15  328.53
54   Books & Media     Software        VPN Premium 1Y    22.73    4.59
56   Books & Media     Software        VPN Premium 1Y   635.97  192.39
60   Books & Media     Software         Antivirus Pro   738.72   37.71
65   Books & Media     Software  Microsoft Office 365    99.85   12.45
70   Books & Media     Software   Photo Editing Suite   190.72   54.24
76   Books & Media     Software        VPN Premium 1Y   348.26   80.36
83   Books & Media     Software   Photo Editing Suite   173.44   83.92
85   Books & Media     Software   Photo Editing Suite    56.51   -8.51
88   Books & Media     Software   Photo Editing Suite   201.47   17.81
102  Books & Media     Software  Microsoft Office 365   172.81   67.91
115  Books & Media     Software  Microsoft Office 365   196.51   -3.29
124  Books & Media     Software   Photo Editing Suite   444.75  195.46
149  Books & Media     Software         Antivirus Pro    56.11   -1.19
153  Books & Media     Software  Adobe Creative Cloud    21.47    6.90
158  Books & Media     Software  Adobe Creative Cloud    40.35   10.55
161  Books & Media     Software  Adobe Creative Cloud    22.13    6.08
219  Books & Media     Software  Microsoft Office 365    27.47   10.93
220  Books & Media     Software  Microsoft Office 365   292.86  123.50